resolver: lts-22.26

packages:
- share-auth
- share-auth/example
- share-utils

extra-deps:
# Bumping hasql up to get Pipelining mode
- hasql-1.8.1.1
- hasql-pool-1.2.0.2
- hasql-interpolate-1.0.1.0
- postgresql-binary-0.14@sha256:3f3518f841cf80b107862800715bc64f43c2c71696c4129f63404c1ff61cc919,4025
- postgresql-libpq-0.10.1.0@sha256:6a45edff0a9e30b32cda6e443107950492322622c4fbefc8fb4dcf6452dcf0b4,3203

ghc-options:
 # All packages
 "$locals": -Wall -Wno-name-shadowing -Wno-missing-pattern-synonym-signatures -fprint-expanded-synonyms -fwrite-ide-info
 statistics: -fsimpl-tick-factor=10000 # statistics fails on GHC 9 without this, https://github.com/haskell/statistics/issues/173
