resolver: lts-20.26

packages:
- .
- share-auth
- share-auth/example
- share-utils
- unison/codebase2/codebase
- unison/codebase2/codebase-sqlite
- unison/codebase2/codebase-sqlite-hashing-v2
- unison/codebase2/codebase-sync
- unison/codebase2/core
- unison/codebase2/util-serialization
- unison/codebase2/util-term
- unison/lib/orphans/network-uri-orphans-sqlite
- unison/lib/orphans/unison-core-orphans-sqlite
- unison/lib/orphans/unison-hash-orphans-aeson
- unison/lib/orphans/unison-hash-orphans-sqlite
- unison/lib/orphans/uuid-orphans-sqlite
- unison/lib/unison-hash
- unison/lib/unison-hashing
- unison/lib/unison-prelude
- unison/lib/unison-pretty-printer
- unison/lib/unison-sqlite
- unison/lib/unison-util-base32hex
- unison/lib/unison-util-bytes
- unison/lib/unison-util-cache
- unison/lib/unison-util-file-embed
- unison/lib/unison-util-relation
- unison/lib/unison-util-rope
- unison/parser-typechecker
- unison/unison-core
- unison/unison-hashing-v2
- unison/unison-share-api
- unison/unison-share-projects-api
- unison/unison-syntax
- unison/yaks/easytest

extra-deps:
# wrong version in snapshot
- resource-pool-0.3.1.0@sha256:dbaadfcc3c1be5391336e2016b28bb2d0c534f245ba9f5af5ed1d5125afc8c1a,1280
- fuzzyfind-3.0.1@sha256:78f89c1d79adf0a15fa2e57c693d42b4765ccfbbe380d0c9d7da6bff9f124f85,1823
- guid-0.1.0@sha256:a7c975be473f6f142d5cc1b39bc807a99043d20b1bb0873fdfe7a3ce84d2faf1,1078
- lock-file-0.7.0.0@sha256:3ad84b5e454145e1d928063b56abb96db24a99a21b493989520e58fa0ab37b00,4484
- monad-validate-1.2.0.1@sha256:5a100da896f11ca4b7c123da85decbedeb46c37054a097f258ac911e715cb68d,2587
- raven-haskell-0.1.4.1@sha256:0d27e37968327faba577558a2ee4465ebfd3b6929b09cf4881dfa62a6873c85a,1393
- recover-rtti-0.4.2@sha256:c179a303921126d8d782264e14f386c96e54a270df74be002e4c4ec3c8c7aebd,4529
- strings-1.1@sha256:0285dec4c8ab262359342b3e5ef1eb567074669461b9b38404f1cb870c881c5c,1617
- hasql-interpolate-0.2.1.0@sha256:1cf2a01e83d155fabc6ae3e686c75dfe174cbc3addbe7c8ec55fe17368a3458c,3103
- network-udp-0.0.0@sha256:408d2d4fa1a25e49e95752ee124cca641993404bb133ae10fb81daef22d876ae,1075

ghc-options:
 # All packages
 "$locals": -Wall -Wno-name-shadowing -Wno-missing-pattern-synonym-signatures -fprint-expanded-synonyms -fwrite-ide-info
 statistics: -fsimpl-tick-factor=10000 # statistics fails on GHC 9 without this, https://github.com/haskell/statistics/issues/173
